
[supers]

	[supers.super1]
		#How far forward the first level of the watering can's super will extend
		#Range: -64 ~ 64
		forward = 2
		#How far back the first level of the watering can's super will extend
		#Range: -64 ~ 64
		back = 0
		#How far left the first level of the watering can's super will extend
		#Range: -64 ~ 64
		left = 0
		#How far right the first level of the watering can's super will extend
		#Range: -64 ~ 64
		right = 0

	[supers.super2]
		#How far forward the second level of the watering can's super will extend
		#Range: -64 ~ 64
		forward = 2
		#How far back the second level of the watering can's super will extend
		#Range: -64 ~ 64
		back = 0
		#How far left the second level of the watering can's super will extend
		#Range: -64 ~ 64
		left = 1
		#How far right the second level of the watering can's super will extend
		#Range: -64 ~ 64
		right = 1

	[supers.super3]
		#How far forward the third level of the watering can's super will extend
		#Range: -64 ~ 64
		forward = 4
		#How far back the third level of the watering can's super will extend
		#Range: -64 ~ 64
		back = 0
		#How far left the third level of the watering can's super will extend
		#Range: -64 ~ 64
		left = 1
		#How far right the third level of the watering can's super will extend
		#Range: -64 ~ 64
		right = 1

	[supers.super4]
		#How far forward the fourth level of the watering can's super will extend
		#Range: -64 ~ 64
		forward = 4
		#How far back the fourth level of the watering can's super will extend
		#Range: -64 ~ 64
		back = 0
		#How far left the fourth level of the watering can's super will extend
		#Range: -64 ~ 64
		left = 2
		#How far right the fourth level of the watering can's super will extend
		#Range: -64 ~ 64
		right = 2

[nether]
	#Allow watering cans to work in the Nether.
	allow = false
	#Allows the Netherite Watering Can to be used in the nether, regardless of the previous option.
	allowNetheriteCanAnyways = true

[interactions]
	#Whether watering cans extinguish fires & campfires.
	extinguishFires = true
	#The chance out of 100 that dirt is converted into mud, 0 will disable the mechanic.
	#Range: 0 ~ 100
	mudOdds = 0
	#The chance out of 100 that bonemeal is applied to a watered crop, 0 will disable the mechanic.
	#Range: 0 ~ 100
	bonemealOdds = 0

