#Whether to stop crop trampling
noTrample = true
#Whether to stop random ticks (Water from source blocks and moisture decay)
noRandomTick = true
#When enabled, farmland will not check for blocks above it, and can be built on top of without turning to dirt
sturdyFarmland = true
#If splash water potions can be used to moisten farmland
splashPotionWatering = true
#The range of splash water bottles for watering, 0 to water only the block hit
#Range: 0 ~ 8
splashWaterArea = 1
#If buckets can be used to moisten farmland
bucketWatering = true
#If bottles can be used to moisten farmland
bottleWatering = true
#If rain will moisten farmland
rainWatering = true
#If the farmland will decay daily
dailyReset = true
#The time of day daily reset logic will occur (within 10 ticks)
#Range: 0 ~ 24000
dailyTimeMin = 5
#The chance that farmland will become dry
#Range: 0 ~ 100
dailyDryChance = 100
#The chance that dry farmland will decay into dirt
#Range: 0 ~ 100
dailyDecayChance = 50
#If shovels can turn farmland to dirt when right clicking
shovelReverting = true
#If crops should check for blocks with sprinkler tags to prevent drying
checkSprinklers = true
#Crops will not factor in greenhouse glass if a #dewdrop:waterable farmland is between them 
strictGreenhouses = true

