
[hook_stats]

	#Wood Hook Stats
	[hook_stats.wood]
		#The number of hooks
		#Range: > 1
		count = 1
		#The hooks range
		#Range: 1.0 ~ 1.7976931348623157E308
		range = 16.0
		#The hooks shooting speed
		#Range: 0.1 ~ 1.7976931348623157E308
		travelSpeed = 12.0
		#How fast the hook pulls the player
		#Range: 0.1 ~ 1.7976931348623157E308
		pullSpeed = 6.0
		#Should the hook provide creative flight or not
		creativeFlight = false

	#Iron Hook Stats
	[hook_stats.iron]
		#The number of hooks
		#Range: > 1
		count = 2
		#The hooks range
		#Range: 1.0 ~ 1.7976931348623157E308
		range = 32.0
		#The hooks shooting speed
		#Range: 0.1 ~ 1.7976931348623157E308
		travelSpeed = 24.0
		#How fast the hook pulls the player
		#Range: 0.1 ~ 1.7976931348623157E308
		pullSpeed = 12.0
		#Should the hook provide creative flight or not
		creativeFlight = false

	#Diamond Hook Stats
	[hook_stats.diamond]
		#The number of hooks
		#Range: > 1
		count = 4
		#The hooks range
		#Range: 1.0 ~ 1.7976931348623157E308
		range = 64.0
		#The hooks shooting speed
		#Range: 0.1 ~ 1.7976931348623157E308
		travelSpeed = 48.0
		#How fast the hook pulls the player
		#Range: 0.1 ~ 1.7976931348623157E308
		pullSpeed = 24.0
		#Should the hook provide creative flight or not
		creativeFlight = false

	#Red Hook Stats
	[hook_stats.red]
		#The number of hooks
		#Range: > 1
		count = 3
		#The hooks range
		#Range: 1.0 ~ 1.7976931348623157E308
		range = 20.0
		#The hooks shooting speed
		#Range: 0.1 ~ 1.7976931348623157E308
		travelSpeed = 8.0
		#How fast the hook pulls the player
		#Range: 0.1 ~ 1.7976931348623157E308
		pullSpeed = 6.0
		#Should the hook provide creative flight or not
		creativeFlight = true

	#Blaze Hook Stats
	[hook_stats.blaze]
		#The number of hooks
		#Range: > 1
		count = 2
		#The hooks range
		#Range: 1.0 ~ 1.7976931348623157E308
		range = 64.0
		#The hooks shooting speed
		#Range: 0.1 ~ 1.7976931348623157E308
		travelSpeed = 1920.0
		#How fast the hook pulls the player
		#Range: 0.1 ~ 1.7976931348623157E308
		pullSpeed = 36.0
		#Should the hook provide creative flight or not
		creativeFlight = false

	#Ender Hook Stats
	[hook_stats.ender]
		#The number of hooks
		#Range: > 1
		count = 1
		#The hooks range
		#Range: 1.0 ~ 1.7976931348623157E308
		range = 96.0
		#The hooks shooting speed
		#Range: 0.1 ~ 1.7976931348623157E308
		travelSpeed = 1920.0
		#How fast the hook pulls the player
		#Range: 0.1 ~ 1.7976931348623157E308
		pullSpeed = 48.0
		#Should the hook provide creative flight or not
		creativeFlight = false

