
#Untitled Duck Mod
[duck]
	#The spawn weight of the duck mob.The higher it is, the higher are the spawn rates. See https://minecraft.fandom.com/wiki/Spawn#Animals for an explanation.
	#Range: > 0
	duck_spawn_weight = 6
	#The minimum number of ducks that should be spawned at once in a group.
	#Range: > 0
	duck_min_group_size = 2
	#The maximum number of ducks that should be spawned at once in a group.
	#Range: > 0
	duck_max_group_size = 4
	#Chance of ducks successfully fishing.
	#Range: 0.0 ~ 1.0
	duck_fishing_change = 0.05

[goose]
	#The spawn weight of the goose mob.The higher it is, the higher are the spawn rates. See https://minecraft.fandom.com/wiki/Spawn#Animals for an explanation.
	#Range: > 0
	goose_spawn_weight = 4
	#The minimum number of geese that should be spawned at once in a group.
	#Range: > 0
	goose_min_group_size = 2
	#The maximum number of geese that should be spawned at once in a group.
	#Range: > 0
	goose_max_group_size = 4

[intimidation]
	#Intimidate effects don't work on mobs in the list
	intimidation_blacklist = ["modid:test"]

