
# Options related to mob spawning
# Whether or not the mob will spawn when breaking blocks defined in json/[mobName]-spawn.json
# Whether or not the mob will spawn when killing entities defined in json/[mobName]-spawn.json
[MobSpawning]

	[MobSpawning.desert_mojo]
		"Desert Mojo Breaking Block Spawn " = false
		"Desert Mojo Killing Entity Spawn " = false

	[MobSpawning.forest_mojo]
		"Forest Mojo Breaking Block Spawn " = false
		"Forest Mojo Killing Entity Spawn " = false

	[MobSpawning.hound]
		"Hound Breaking Block Spawn " = false
		"Hound Killing Entity Spawn " = false

	[MobSpawning.Scarecrow]
		"Scarecrow Breaking Block Spawn " = false
		"Scarecrow Killing Entity Spawn " = false

	[MobSpawning.scorpion]
		"Scorpion Breaking Block Spawn " = false
		"Scorpion Killing Entity Spawn " = false

	[MobSpawning.scorpion_baby]
		"Baby Scorpion Breaking Block Spawn " = false
		"Baby Scorpion Killing Entity Spawn " = false

	[MobSpawning.wisp]
		"Wisp Breaking Block Spawn " = false
		"Wisp Killing Entity Spawn " = false
		"Wisp Purse Xp Reward Range " = [30, 30]

	[MobSpawning.nether_wisp]
		"Nether Wisp Breaking Block Spawn " = false
		"Nether Wisp Killing Entity Spawn " = false
		"Nether Wisp Purse Xp Reward Range " = [80, 80]

	[MobSpawning.ender_wisp]
		"Ender Wisp Breaking Block Spawn " = false
		"Ender Wisp Killing Entity Spawn " = false
		"Ender Wisp Purse Xp Reward Range " = [240, 240]

	[MobSpawning.corpse_eater]
		"Corpse Eater Breaking Block Spawn " = false
		"Corpse Eater Killing Entity Spawn " = false

	[MobSpawning.peacock_spider]
		"Peacock Spider Breaking Block Spawn " = false
		"Peacock Spider Killing Entity Spawn " = false

	[MobSpawning.bullfrog]
		"Bullfrog Breaking Block Spawn " = false
		"Bullfrog Killing Entity Spawn " = false

