// priority: 0
global.husbandryAnimals = [
  "minecraft:cow",
  "minecraft:goat",
  "minecraft:sheep",
  "minecraft:pig",
  "snowpig:snow_pig",
  "minecraft:rabbit",
  "meadow:wooly_cow",
  "meadow:wooly_sheep",
  "meadow:water_buffalo",
  "minecraft:chicken",
  "untitledduckmod:duck",
  "untitledduckmod:goose",
  "autumnity:turkey",
  "autumnity:snail",
  "minecraft:mooshroom",
  "buzzier_bees:moobloom",
  "minecraft:sniffer",
  "etcetera:chapple",
  "minecraft:panda",
  "species:mammutilation",
  "snuffles:snuffle",
  "species:goober",
  "farmlife:domestic_tribull",
  "wildernature:minisheep",
  "wildernature:deer",
  "wildernature:raccoon",
  "wildernature:bison",
  "minecraft:chicken",
  "untitledduckmod:duck",
  "untitledduckmod:goose",
  "etcetera:chapple",
  "autumnity:turkey",
  "species:wraptor",
  "wildernature:flamingo",
  "wildernature:penguin",
  "farmlife:galliraptor",
  "minecraft:frog",
  "wildernature:squirrel",
  "atmospheric:cochineal",
  "minecraft:squid",
  "minecraft:glow_squid",
  "crittersandcompanions:red_panda",
  "windswept:frostbiter",
];

global.animalMessageSettings = `{anchor:"BOTTOM_CENTER",background:1,wrap:220,align:"BOTTOM_CENTER",color:"#FF5555",offsetY:-80}`;
