
[Features]
	#Should placeable tooltips be enabled?
	Tooltips = true
	#Should a message be enabled when attempting to place a food item?
	Display-Message = true
	#Disable Vanila Food(mushroom stew,rabbit stew,beetroot soup) Placement. Set to true if vanila food placement conflicts with other mods
	Disable-Vanila-Food-Placement = false
	#This mod uses hardcoded check to remove annoying eating animation while plating some foods.
	# Try setting this to true if there are any related issues(can't eat foods, can't plate foods, etc.). (only applicable for Forge version)
	Disable-Eating-Animation-Fix = false

