#Whether claims are currently shown, toggleable from the fullscreen map
show_claims = true
#Whether forceloaded chunks are marked with an outline (only if claims are shown)
show_forceloads = true
#Whether claim owners are shown when hovering over a chunk
show_claimant = true
#Opacity of a claim on the map (0 is invisible)
#Range: 0.0 ~ 1.0
claim_opacity = 0.25
#Opacity of the forceload marker (0 is invisible)
#Range: 0.0 ~ 1.0
forceload_opacity = 1.0
#Thickness of the forceload marker (in pixels)
#Range: 0.0 ~ 16.0
forceload_stroke = 3.0
#Opacity of the claimable area outline (0 is invisible)
#Range: 0.0 ~ 1.0
valid_area_opacity = 0.5

