
[logbegone]
	phrases = ["mod.schnappdragon.snuffles.core.registry.SnufflesItems", "mod.schnappdragon.snuffles.core.registry.SnufflesItems:registerCreativeTabsItem:", "Registering S2C receiver with id wildernature:screen_update", "Registry entry listened Registry Entry", "Disconnecting VANILLA connection attempt", "Channels ", "farmlife:platefish", "Failed to deserialize gossips: Not a list: END", "EMI", "was not registered", "Something went wrong. Could not find JEI Search Text Field object", "Received passengers for unknown entity"]
	regex = ["Disconnecting VANILLA connection attempt", "Channels ", "has no attributes", "ending event! brewery"]

