#determine how often will Burneds spawn
burnedWeight = 0
#determine how often will Frostbittens spawn
frostbittenWeight = 0
#determine how often will Glacial Hunters spawn
glacialHunterWeight = 0
#determine how often will Swampies spawn
swampyWeight = 0
#determine how often will Undead Miners spawn
undeadMinerWeight = 0
#determine the max y height where Undead Miners can spawn
undeadMinerDepth = 0
#determine how often will Mummies spawn
mummyWeight = 0
#determine how often will Dead Beard spawn
deadBeardWeight = 0
#determine the chance of spawning for Immortals
immortalChance = 0.0

