
["Villager Settings"]
	#Enable Veggies Delight villager trades
	enableVillagerTrades = false
	#Enable Veggies Delight Wandering Trader trades
	enableWanderingTrades = false

["Village Settings"]
	#Enable Veggies Delight village structures
	generateVillageStructures = false

