
[Settings]
	#Enable Toast Control
	"Toast Control" = true
	#**Extremely Experimental** Automatically Register categories and set the icon ** Overrides IconMappings.json **
	"Auto Register Data" = true
	#The Max Amount Of Toasts To Display (Ignored If Toast Control Is Enabled)
	#Range: 1 ~ 5
	"Max Toasts" = 1
	#The Direction Of The Toast Animation Options Are Left/Right (Direction It Come in From Left, Right, Top, Down
	"Animation Direction" = "Down"
	#The Left / Right Offset Of The Toast
	"Base X" = -4
	#The Up / Down Offset Of The Toast
	"Base Y" = 14
	#How long (in ms) a stacked/updated XP toast stays visible after the last gain
	#Range: 100 ~ 10000
	"Stack XP Timer" = 5000
	#How long (in ms) the toast animation takes to complete(Ignored if Toast Control Is Enabled
	#Range: 100 ~ 10000
	"Animation Time" = 1000
	#Should the toasts slide out of the way when they are added?
	"No Slide" = false
	#Should the title be translucent
	"Title Translucent" = false
	#Should the exp amount be translucent
	"Exp Translucent" = false
	#Should the background be translucent
	"Background Translucent" = false
	#Should the background be disabled
	"Disable Background" = true
	#Horizontal pixel offset for the icon
	#Range: 0 ~ 100
	"Icon X Offset" = 14
	#Vertical pixel offset for the icon
	#Range: 0 ~ 100
	"Icon Y Offset" = 2
	#Enable The Built-In File Watcher, Checks If This File Is Modified And Reloads The Config(Bypass Forge Reloading)
	"Enable File Watcher" = false
	#Completely Disable The Client Side Functionality
	"Disable Toasts" = false

["Text Settings"]
	#The Title Part To Display
	Title = "%title%"
	#The Exp Part Of The Message
	Exp = " +%exp% xp"
	#Should the text be forced to be inline
	"Force Inline" = true
	#The Alpha Of The Title
	#Range: 0 ~ 255
	"Title Alpha" = 127
	#The Alpha Of The Exp Amount
	#Range: 0 ~ 255
	"Exp Alpha" = 127
	#Where to anchor toasts on screen: "top-left", "top-center", "top-right",
	#"middle-left", "middle-center", "middle-right",
	#"bottom-left", "bottom-center", "bottom-right"
	"Anchor Position" = "bottom-left"
	#The Size Of The Title
	#Range: 1 ~ 32
	"Title Size" = 6
	#The Size Of The Exp Amount
	#Range: 1 ~ 32
	"Exp Size" = 6
	#The Size Of The Icon
	#Range: 1 ~ 32
	"Icon Size" = 12
	#The Height Of The Background
	#Range: 1 ~ 1000
	"Background Height" = 16
	#The Width Of The Background
	#Range: 1 ~ 1000
	"Background Width" = 160

	["Text Settings"."Text Style"]
		#The Color Of The Title
		"Title Color" = 16755200
		#The Color Of The Exp Amount
		"Exp Color" = 16755200
		#Should The Title Be Bold
		"Bold Title" = false
		#Should The Exp Amount Be Bold
		"Bold Exp" = false
		#Should The Title Have A Drop Shadow
		"Title Drop Shadow" = false
		#Should The Exp Amount Have A Drop Shadow
		"Exp Drop Shadow" = false
		#The Color Of The Exp Amount Drop Shadow
		"Exp Drop Shadow Color" = 0
		#The Color Of The Title Drop Shadow
		"Title Drop Shadow Color" = 0

[Sounds]
	#Disable All Sounds Made By Toast
	"Disable Toast Sounds" = true
	#A list of "dimension=sound_event" entries for the toast-in sound
	"Sound Mapping In" = ["minecraft:overworld=minecraft:ui.toast.in", "minecraft:the_nether=minecraft:ui.toast.in", "minecraft:the_end=minecraft:ui.toast.in"]
	#A list of "dimension=sound_event" entries for the toast-out sound
	"Sound Mapping Out" = ["minecraft:overworld=minecraft:ui.toast.out", "minecraft:the_nether=minecraft:ui.toast.out", "minecraft:the_end=minecraft:ui.toast.out"]

